use std::fmt;

pub enum ClassJob {
    Gladiator,
    Pugilist,
    Marauder,
    Lancer,
    Archer,
    Conjurer,
    Thaumaturge,
    Carpenter,
    Blacksmith,
    Armorer,
    Goldsmith,
    Leatherworker,
    Weaver,
    Alchemist,
    Culinarian,
    Miner,
    Botanist,
    Fisher,
    Paladin,
    Monk,
    Warrior,
    Dragoon,
    Bard,
    WhiteMage,
    BlackMage,
    Arcanist,
    Summoner,
    Scholar,
    Rogue,
    Ninja,
    Machinist,
    DarkKnight,
    Astrologian,
    Samurai,
    RedMage,
    BlueMage,
    Gunbreaker,
    Dancer,
    Unknown(u8),
}

impl From<u8> for ClassJob {
    fn from(value: u8) -> Self {
        match value {
            1 => ClassJob::Gladiator,
            2 => ClassJob::Pugilist,
            3 => ClassJob::Marauder,
            4 => ClassJob::Lancer,
            5 => ClassJob::Archer,
            6 => ClassJob::Conjurer,
            7 => ClassJob::Thaumaturge,
            8 => ClassJob::Carpenter,
            9 => ClassJob::Blacksmith,
            10 => ClassJob::Armorer,
            11 => ClassJob::Goldsmith,
            12 => ClassJob::Leatherworker,
            13 => ClassJob::Weaver,
            14 => ClassJob::Alchemist,
            15 => ClassJob::Culinarian,
            16 => ClassJob::Miner,
            17 => ClassJob::Botanist,
            18 => ClassJob::Fisher,
            19 => ClassJob::Paladin,
            20 => ClassJob::Monk,
            21 => ClassJob::Warrior,
            22 => ClassJob::Dragoon,
            23 => ClassJob::Bard,
            24 => ClassJob::WhiteMage,
            25 => ClassJob::BlackMage,
            26 => ClassJob::Arcanist,
            27 => ClassJob::Summoner,
            28 => ClassJob::Scholar,
            29 => ClassJob::Rogue,
            30 => ClassJob::Ninja,
            31 => ClassJob::Machinist,
            32 => ClassJob::DarkKnight,
            33 => ClassJob::Astrologian,
            34 => ClassJob::Samurai,
            35 => ClassJob::RedMage,
            36 => ClassJob::BlueMage,
            37 => ClassJob::Gunbreaker,
            38 => ClassJob::Dancer,
            _ => ClassJob::Unknown(value),
        }
    }
}

impl fmt::Display for ClassJob {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                ClassJob::Gladiator => "GLA",
                ClassJob::Pugilist => "PGL",
                ClassJob::Marauder => "MRD",
                ClassJob::Lancer => "LNC",
                ClassJob::Archer => "ARC",
                ClassJob::Conjurer => "CNJ",
                ClassJob::Thaumaturge => "THM",
                ClassJob::Carpenter => "CRP",
                ClassJob::Blacksmith => "BSM",
                ClassJob::Armorer => "ARM",
                ClassJob::Goldsmith => "GSM",
                ClassJob::Leatherworker => "LTW",
                ClassJob::Weaver => "WVR",
                ClassJob::Alchemist => "ALC",
                ClassJob::Culinarian => "CUL",
                ClassJob::Miner => "MIN",
                ClassJob::Botanist => "BTN",
                ClassJob::Fisher => "FSH",
                ClassJob::Paladin => "PLD",
                ClassJob::Monk => "MNK",
                ClassJob::Warrior => "WAR",
                ClassJob::Dragoon => "DRG",
                ClassJob::Bard => "BRD",
                ClassJob::WhiteMage => "WHM",
                ClassJob::BlackMage => "BLM",
                ClassJob::Arcanist => "ACN",
                ClassJob::Summoner => "SMN",
                ClassJob::Scholar => "SCH",
                ClassJob::Rogue => "ROG",
                ClassJob::Ninja => "NIN",
                ClassJob::Machinist => "MCH",
                ClassJob::DarkKnight => "DRK",
                ClassJob::Astrologian => "AST",
                ClassJob::Samurai => "SAM",
                ClassJob::RedMage => "RDM",
                ClassJob::BlueMage => "BLU",
                ClassJob::Gunbreaker => "GNB",
                ClassJob::Dancer => "DNC",
                ClassJob::Unknown(value) => return write!(f, "UnknownClassJob({:x})", value),
            }
        )
    }
}
