Local $actionMap = ObjCreate("Scripting.Dictionary")

; Add keybinds below
; (Add comments on what sections they're in?)
; Shortcuts -> Crafting Log
$actionMap.Add("Crafting Log",			"n")
; System -> Cycle through UI Component Tabs (Back)
$actionMap.Add("Cycle Backward",			"[")
; System -> Cycle through UI Component Tabs (Forward)
$actionMap.Add("Cycle Forward",				"]")
; System -> Confirm
$actionMap.Add("Confirm",					"=")

; For modifer combinations use + for SHIFT and ^ for CTRL
$actionMap.Add("Advanced Touch",            "^3")
$actionMap.Add("Basic Synthesis",           "^c")
$actionMap.Add("Basic Touch",               "^6")
$actionMap.Add("Byregot's Blessing",        "f")
$actionMap.Add("Byregot's Brow",        	"v")
$actionMap.Add("Byregot's Miracle",			"^3")
$actionMap.Add("Careful Synthesis II",      "1")
$actionMap.Add("Careful Synthesis III",     "2")
$actionMap.Add("Comfort Zone",              "x")
$actionMap.Add("Focused Synthesis",			"+v")
$actionMap.Add("Focused Touch", 			"+g")
$actionMap.Add("Great Strides",             "e")
$actionMap.Add("Hasty Touch II",            "4")
$actionMap.Add("Hasty Touch",               "C")
$actionMap.Add("Ingenuity II",              "q")
$actionMap.Add("Ingenuity",					"+t")
$actionMap.Add("Initial Preparations", 		"+x")
$actionMap.Add("Inner Quiet",               "c")
$actionMap.Add("Innovation",                "r")
$actionMap.Add("Manipulation II",           "t")
$actionMap.Add("Master's Mend II",          "X")
$actionMap.Add("Master's Mend",             "^g")
$actionMap.Add("Muscle Memory", 			"+c")
$actionMap.Add("Observe",              		"+z")
$actionMap.Add("Patient Touch",             "^4")
$actionMap.Add("Piece by Piece", 			"+e")
$actionMap.Add("Precise Touch",             "^5")
$actionMap.Add("Prudent Touch",             "5")
$actionMap.Add("Rumination", 				"+r")
$actionMap.Add("Specialty: Reflect",		"+f")
$actionMap.Add("Standard Synthesis",        "^x")
$actionMap.Add("Standard Touch",            "^s")
$actionMap.Add("Steady Hand II",            "z")
$actionMap.Add("Tricks of the Trade",       "g")
$actionMap.Add("Waste Not II",              "^f")
