# This file contains example macros to use as a basis for configuring how to
# craft items. Each [[xiv_macro]] corresponds to a specific macro and *must*
# contain a name, durability, and list of actions. max_rlvl, min_rlvl,
# difficulty, and specialist are optional.
#
# Durability is a list of comma-separated durability values the macro can be
# used for. For example, the following would allow the macro to be selected
# for 35 and 40 durability recipes.
#   durability = [ 35, 40 ]
#
# Optional fields supported are
# max_rlvl = <number>
#   - This macro is for recipes with a recipe level <= max_rlvl.
# min_rlvl = <number>
#   - This macro is for recipes with a recipe level >= min_rlvl.
# difficulty = <number>
#   - The listed difficulty of the macro. This is referred to as 'Progress' on
#     garlandtools and Teamcraft, but 'Difficulty' in-game on the recipe.
# specialist = <true|false> (defaults to false)
#   - This macro should only be used of the recipe's job is configured as a specialist
#

# This macro will work for any recipe below level 70 of any durability. For macros of different
# level ranges you can gate by min_rlvl and max_rlvl as necessary.
[[xiv_macro]]
name = "1 - 70 HQ"
max_rlvl = 70
durability = [ 35, 40, 60, 70, 80 ]
actions = """
/ac "Trained Eye" <wait.3>
/ac "Veneration" <wait.2>
/ac "Groundwork" <wait.3>
"""
